site_name: Explaining the Model Context Protocol (MCP) — How AI Tools Talk to Each Other
site_url: https://bicep.github.io/ol-demo
theme:
  name: material
  palette:
    primary: 'orange'
    accent: 'deep-orange'
  features:
    - navigation.tabs
    - navigation.sections
    - mermaid 
nav:
  - Home: index.md
  - About me: about-me.md
  - Presentation: mcp-presentation.html
  - A Concrete Example: a-concrete-example.md
markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: true
  - attr_list
  - def_list
  - pymdownx.superfences
  - pymdownx.extra:
      pymdownx.superfences:
        custom_fences:
          - name: mermaid       # 🟨 Recognize ```mermaid blocks
            class: mermaid      # 🟨 Add proper CSS class
            format: !!python/name:pymdownx.superfences.fence_code_format  # 🟨 Use default formatter

  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
plugins:
  - search
  - mermaid2
